/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Graph.*;
import java.awt.*;

/**
 *
 * @author lenovo
 */
public class DrawPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
        initComponents();
    }
    
    
    public DrawPanel(MyGraph g){
        this();
        this.graph=g;
    }
    
    
    public void setImage(Image i){
        this.image=i;
    }
    
    
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        
        if(image!=null)
            //drawImage(Image img, int x, int y, Color bgcolor, ImageObserver observer)
            //绘制指定图像中当前可用的图像。图像的左上角位于该图形上下文坐标空间的 (x, y)
            //img - 要绘制的指定图像。如果 img 为 null，则此方法不执行任何动作。
            //x - x 坐标。
            //y - y 坐标。
            //observer - 当转换了更多图像时要通知的对象。 
            g.drawImage(image,0,0,this);
        if(graph!=null)
            graph.displayAll(g);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    MyGraph graph;
    Image image;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
