
package UI;

import Graph.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import main.GraphApp;

/**
 *
 * @author pipi
 */
public class Toolbar extends JToolBar {
    

    public Toolbar() {
    }

    
    public Toolbar(MyGraph g) {
        this.graph=g;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jComboBox1 = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jButton8 = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jButton9 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jButton6 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButton7 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setText("No");
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton1);

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setText("Circle");
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton2);

        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setText("Rectangle");
        jToggleButton3.setFocusable(false);
        jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton3);

        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setText("Triangle");
        jToggleButton4.setFocusable(false);
        jToggleButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton4);

        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setText("Square");
        jToggleButton5.setFocusable(false);
        jToggleButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton5);

        buttonGroup1.add(jToggleButton6);
        jToggleButton6.setText("Pentagon");
        jToggleButton6.setFocusable(false);
        jToggleButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton6);

        buttonGroup1.add(jToggleButton7);
        jToggleButton7.setText("Line");
        jToggleButton7.setFocusable(false);
        jToggleButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton7);

        buttonGroup1.add(jToggleButton8);
        jToggleButton8.setText("Text");
        jToggleButton8.setFocusable(false);
        jToggleButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton8);
        jToolBar1.add(jSeparator1);

        jButton1.setText("Add");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(Toolbar.graph.shape));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jComboBox1);
        jToolBar1.add(jSeparator2);

        jButton2.setText("Delete");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator4);

        jButton3.setText("Edit");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator9);

        jButton8.setText("Savetxt");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);
        jToolBar1.add(jSeparator10);

        jButton9.setText("Loadtxt");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton9);
        jToolBar1.add(jSeparator5);

        jButton4.setText("SaveObject");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator6);

        jButton5.setText("LoadObject");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);
        jToolBar1.add(jSeparator7);

        jButton6.setText("SaveImage");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);
        jToolBar1.add(jSeparator8);

        jButton7.setText("LoadImage");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        select=0;
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        select=1;
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        select=2;
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        select=3;
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        select=4;
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        select=5;
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        select=6;   
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        select=7;
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    //add graph
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //add graph
        switch (select)
        {
            case 0://No
                JOptionPane.showMessageDialog(getParent(), "No shape type setted");
                break;
                
            case 1://Circle
                CreatCircle();
                break;
                
            case 2://Rectangle
                CreatRectangle();
                break;
                
            case 3://Triangle
                CreatTriangle();
                break;
                
            case 4://Square
                CreatSquare();
                break;
                
            case 5://Pentagon
                CreatPentagon();
                break;
                
            case 6://Line
                CreatLine();
                break;
                
            case 7://Text
                CreatText();
                break;
                
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    //delete graph
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        //delete graph
        int i=jComboBox1.getSelectedIndex();
        if(i!=-1)Toolbar.graph.remove(i);
        if(Toolbar.graph.size()==0)
            jComboBox1.setSelectedIndex(-1);
        else if(i<Toolbar.graph.size())
            jComboBox1.setSelectedIndex(i);
        getParent().repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    //edit graph
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //获得要修改的图形的索引
        int i=jComboBox1.getSelectedIndex();
        if(i!=-1){
            
            MyShape s=graph.get(i);
            //edit Circle
            if(s instanceof Circle)
            {
                Circle c=(Circle)CircleInputDialog.getCircle((Frame)(getRootPane().getParent()),(Circle)s);
                if(c!=null)
                {
                    ((Circle)s).setX(c.getX());
                    ((Circle)s).setY(c.getY());
                    ((Circle)s).setR(c.getR());
                }
            }
            //edit Rectangle
            else if(s instanceof Graph.Rectangle)
            {
                Graph.Rectangle r=(Graph.Rectangle)RectangleInputDialog.getRectangle((Frame)(getRootPane().getParent()),(Graph.Rectangle)s);
                if(r!=null)
                {
                    ((Graph.Rectangle)s).setX(r.getX());
                    ((Graph.Rectangle)s).setY(r.getY());
                    ((Graph.Rectangle)s).setLength(r.getLength());
                    ((Graph.Rectangle)s).setWidth(r.getWidth());
                }
            }
            //edit Triangle
            else if(s instanceof Triangle)
            {
                Triangle t=(Triangle)TriangleInputDialog.getTriangle((Frame)(getRootPane().getParent()),(Triangle)s);
                if(t!=null)
                {
                    ((Triangle)s).setX0(t.getX0());
                    ((Triangle)s).setY0(t.getY0());
                    ((Triangle)s).setX1(t.getX1());
                    ((Triangle)s).setY1(t.getY1());
                    ((Triangle)s).setX2(t.getX2());
                    ((Triangle)s).setY2(t.getY2());
                }
            }
            //edit Square
            else if(s instanceof Square)
            {
                Square sq=(Square)SquareInputDialog.getSquare((Frame)(getRootPane().getParent()),(Square)s);
                if(sq!=null)
                {
                    ((Square)s).setX(sq.getX());
                    ((Square)s).setY(sq.getY());
                    ((Square)s).setSide(sq.getSide());
                }
            }
            //edit Pentagon
            else if(s instanceof Pentagon)
            {
                Pentagon p=(Pentagon)PentagonInputDialog.getPentagon((Frame)(getRootPane().getParent()),(Pentagon)s);
                if(p!=null)
                {
                    ((Pentagon)s).setX0(p.getX0());
                    ((Pentagon)s).setY0(p.getY0());
                    ((Pentagon)s).setX1(p.getX1());
                    ((Pentagon)s).setY1(p.getY1());
                    ((Pentagon)s).setX2(p.getX2());
                    ((Pentagon)s).setY2(p.getY2());
                    ((Pentagon)s).setX3(p.getX3());
                    ((Pentagon)s).setY3(p.getY3());
                    ((Pentagon)s).setX4(p.getX4());
                    ((Pentagon)s).setY4(p.getY4());
                }
            }
            //edit Line
            else if(s instanceof Line)
            {
                Line l=(Line)LineInputDialog.getLine((Frame)(getRootPane().getParent()),(Line)s);
                if(l!=null)
                {
                    ((Line)s).setX1(l.getX1());
                    ((Line)s).setY1(l.getY1());
                    ((Line)s).setX2(l.getX2());
                    ((Line)s).setY2(l.getY2());
                }
            }
            //edit Text
            else if(s instanceof Text)
            {
                Text t=(Text)TextInputDialog.getText((Frame)(getRootPane().getParent()),(Text)s);
                if(t!=null)
                {
                    ((Text)s).setText(t.getText());
                }
            }
        }
        getParent().repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    //Save Object
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        try{
            Container f=getRootPane().getParent();
            GraphApp frame=(GraphApp)f;
            java.io.File ff=FileIO.getFile(frame);
            //graph.SaveObject(new java.io.File("graphobjects.bin"));
            graph.SaveObject(ff);
        } 
        catch (IOException e) {
            System.out.println("发生异常:"+e);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    
    //Load Object
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        try{
            Container f=getRootPane().getParent();
            GraphApp frame=(GraphApp)f;
            java.io.File ff=FileIO.getFile(frame);
            graph.ReadObject(ff);
            //graph.ReadObject(new java.io.File("graphobjects.bin"));
            getParent().repaint();
        } 
        catch (Exception ex) {
            System.out.println("图形对象读入结束");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    //Save Image
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        Container f=getRootPane().getParent();
        GraphApp frame=(GraphApp)f;
        SaveImage(frame);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        Container f=getRootPane().getParent();
        if(f!=null)
        {
            GraphApp frame=(GraphApp)f;
            LoadImage(frame);
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    //Save txt
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            Container f=getRootPane().getParent();
            GraphApp frame=(GraphApp)f;
            java.io.File ff=FileIO.getFile(frame);
            graph.Savetxt(ff);
            //graph.Savetxt(new java.io.File("graphs.txt"));
        } 
        catch (IOException ex) {
            Logger.getLogger(GraphApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    //Load txt
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try{
            Container f=getRootPane().getParent();
            GraphApp frame=(GraphApp)f;
            java.io.File ff=FileIO.getFile(frame);
            graph.Readtxt(ff);
            //graph.Readtxt(new java.io.File("graphs.txt"));
            getParent().repaint();
        } 
        catch (IOException ex) {
            Logger.getLogger(GraphApp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    //建立图形
    
    //Add Ciecle
    public void CreatCircle() {
        
        MyShape c=CircleInputDialog.getCircle((Frame)(getRootPane().getParent()));
        if(c!=null) 
        {
            graph.add(c);
            jComboBox1.updateUI();
            getRootPane().getParent().repaint();
        }
        
    }
    
    //Add Rectangle
    public void CreatRectangle() {
    
        MyShape r=RectangleInputDialog.getRectangle((Frame)(getRootPane().getParent()));
        if(r!=null) 
        {
            graph.add(r);
            jComboBox1.updateUI();
            getRootPane().getParent().repaint();
        }
    
    }
    
    //Add Triangle
    public void CreatTriangle() {
    
        MyShape tri=TriangleInputDialog.getTriangle((Frame)(getRootPane().getParent()));
        if(tri!=null) 
        {
            graph.add(tri);
            jComboBox1.updateUI();
            getRootPane().getParent().repaint();
        }
    
    }
    
    //Add Square
    public void CreatSquare() {
    
        MyShape s=SquareInputDialog.getSquare((Frame)(getRootPane().getParent()));
        if(s!=null) 
        {
            graph.add(s);
            jComboBox1.updateUI();
            getRootPane().getParent().repaint();
        }
    
    }
    
    //Add Pentagon
    public void CreatPentagon() {
    
        MyShape p=PentagonInputDialog.getPentagon((Frame)(getRootPane().getParent()));
        if(p!=null) 
        {
            graph.add(p);
            jComboBox1.updateUI();
            getRootPane().getParent().repaint();
        }
    
    }
    
    //Add Line
    public void CreatLine() {
    
        MyShape l=LineInputDialog.getLine((Frame)(getRootPane().getParent()));
        if(l!=null) 
        {
            graph.add(l);
            jComboBox1.updateUI();
            getRootPane().getParent().repaint();
        }
    
    }
    
    //Add Text
    public void CreatText() {
    
        MyShape t=TextInputDialog.getText((Frame)(getRootPane().getParent()));
        if(t!=null) 
        {
            graph.add(t);
            jComboBox1.updateUI();
            getRootPane().getParent().repaint();
        }
    
    }
    
    
    //Save Image
    public void SaveImage(GraphApp frame) {
        
        if(frame!=null)
        {
            
            java.io.File ff=FileIO.getImageFile(frame);
        
            //获得画板的长和宽
            Dimension imageSize = frame.drawPanel1.getSize();  
        
            BufferedImage image = new BufferedImage(imageSize.width,imageSize.height, BufferedImage.TYPE_INT_RGB);
        
            //Graphics2D createGraphics() 创建一个 Graphics2D，可以将它绘制到此 BufferedImage 中。 
            Graphics2D g2D = image.createGraphics();  
        
            frame.drawPanel1.paint(g2D);  
        
            g2D.dispose();  
        
            try {
                String ntype=FileIO.getFileExt(ff);
                javax.imageio.ImageIO.write(image,ntype,ff);  
            } 
            catch (java.io.IOException e) { 
                e.printStackTrace();
                return;
            }  
        }//end if
        
    }
    
    
    public void LoadImage(GraphApp frame) {
        
        java.io.File file=FileIO.getImageFile(frame);
        Image image=null;
        try {
            image=javax.imageio.ImageIO.read(file);  
        }
        catch (java.io.IOException e) {
            e.printStackTrace();return;
        }  
        
        frame.drawPanel1.setImage(image);
        frame.repaint();
        
    }
    
    

    public static MyGraph graph;
    int select=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
