<E> ::= <T> <e>
<e> ::= "+" <T> <e> | "-" <T> <e> | ""
<T> ::= <F> <t>
<t> ::= "*" <F> <t> | "/" <F> <t> | ""
<F> ::= "-" <N> | <N>
<N> ::= <M> <n>
<n> ::= "^" <N> | ""
<M> ::= "(" <E> ")" | <id>
<id> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"